### ISSUE TITLE
Add templates is shown twice when no templates are available

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/text_templates#4]
![image](https://github.com/nextcloud/text_templates/assets/1580193/552995e9-daf1-4537-9553-a665c54a69a8)

![image](https://github.com/nextcloud/text_templates/assets/1580193/c21a7597-7e5f-48ef-8625-9d703512b38f)

Tested on c.nc.c

**Comment by julien-nc** [comment]
Thanks for reporting this!

It's now fixed. The second button is only displayed if the item list is not empty (so the empty content is not there).

Next release coming soon.
