### ISSUE TITLE
No padding in smart picker dialog

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/text_templates#5]
![image](https://github.com/nextcloud/text_templates/assets/1580193/a5414a91-7d35-4464-a6a4-758074a5d399)

compared to talk for example

![image](https://github.com/nextcloud/text_templates/assets/1580193/09f7d4a5-18e6-4fee-aeeb-e0221a843fcb)

Tested on c.nc.c

**Comment by julien-nc** [comment]
This was already fixed but not released.
